language: java

jdk:
  - openjdk8

branches:
  except:
    - gh-pages

before_install:
  - mvn -s .travis.settings.xml -N io.takari:maven:wrapper -Dmaven=3.6.0

install: true

script:
  - ./mvnw -s .travis.settings.xml clean install

cache:
  directories:
    - $HOME/.m2
